import type { Config } from "tailwindcss";
import containerQueries from "@tailwindcss/container-queries";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1c",
        "primary-fixed": "#ffdad6",
        "inverse-on-surface": "#f1f1f1",
        surface: "#f9f9f9",
        "tertiary-container": "#0078bc",
        "secondary-container": "#e2dfde",
        "inverse-surface": "#2f3131",
        "on-tertiary-fixed": "#001d33",
        background: "#f9f9f9",
        "on-surface-variant": "#5d3f3c",
        "on-primary-fixed": "#410002",
        "tertiary-fixed": "#cee5ff",
        tertiary: "#005f95",
        "on-tertiary-fixed-variant": "#004a77",
        "tertiary-fixed-dim": "#97cbff",
        "surface-container-highest": "#e2e2e2",
        outline: "#926e6a",
        "outline-variant": "#e7bdb8",
        "on-error-container": "#93000a",
        "surface-container": "#eeeeee",
        "surface-tint": "#c00014",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-container": "#f8faff",
        "surface-container-high": "#e8e8e8",
        "on-primary": "#ffffff",
        "surface-variant": "#e2e2e2",
        secondary: "#5f5e5e",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#474746",
        "primary-fixed-dim": "#ffb4ab",
        "on-secondary-container": "#636262",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#93000c",
        "on-tertiary": "#ffffff",
        "on-surface": "#1a1c1c",
        "primary-container": "#e21b22",
        error: "#ba1a1a",
        primary: "#b80013",
        "inverse-primary": "#ffb4ab",
        "secondary-fixed": "#e5e2e1",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fff8f7",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
        label: ["var(--font-body)", "sans-serif"],
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
